name: Terraform workflow

on: [push, workflow_dispatch]

jobs:
  apply:
    name: Terraform apply
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-central-1

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Apply
        working-directory: ./terraform
        run: terraform apply -auto-approve

      - name: Ansible installieren
        run: sudo apt-get install -y ansible

      - name: Generiere Ansible Inventory
        working-directory: ./terraform
        run: |
          echo "[webserver]" > ../ansible/ec2Maschinen.ini
          terraform output -json instance_public_ips > meineOutputs.json
          jq -r ".value[]" meineOutputs.json | while read ip; do
            echo "$ip ansible_user=ec2-user ansible_ssh_private_key_file=~/.ssh/awskey.pem" >> ../ansible/ec2Maschinen.ini
          done

      - name: Copy SSH Key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.AWS_SSH_KEY }}" > ~/.ssh/awskey.pem
          chmod 600 ~/.ssh/awskey.pem

      - name: Ansible Playbook ausführen
        working-directory: ./ansible
        run: ansible-playbook -i ec2Maschinen.ini meinPlaybook.yml -vvv

  destroy:
    name: Terraform destroy
    runs-on: ubuntu-latest
    if: github.event_name == 'workflow_dispatch'

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Terraform
        uses: hashicorp/setup-terraform@v3

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{secrets.AWS_ACCESS_KEY_ID}}
          aws-secret-access-key: ${{secrets.AWS_SECRET_ACCESS_KEY}}
          aws-region: eu-central-1

      - name: Terraform Init
        working-directory: ./terraform
        run: terraform init

      - name: Terraform Destroy
        working-directory: ./terraform
        run: terraform destroy -auto-approve
